project:
  type: website
  output-dir: docs
  
manuscript:
  article: index.qmd

website:
  title: "GIS_final"
  navbar:
    left:
      - href: index.qmd
        text: Home
  # sidebar:
  #   contents:
  #     - index.qmd

format:
  html:
    df-print: kable
  pdf: default
  # docx: default
  jats: default

execute:
  freeze: true



